### PR TITLE
Implement Crow Slew and gate

### PR DESCRIPTION
**Pull request by hallmar**
Implement Crow Slew(TLI modifiable) and gate option for 2nd output of Crow.

### CODE REVIEW

**Comment by hallmar** [comment]
Ok finally updated track.lua to fix the retriggering portion of these changes for the Crow clade, only 3 months later. Better late than never!

I've been running it myself for the past 2 months with no issues. 

I cleaned up some minor code for the crow clade that wasn't having any effect.

**Comment by hallmar** [comment]
> Ahhh sorry for being so slow for this - is it ready to merge? I am happy to push it through now.

Yes please! Let me know if you find any glaring bugs :) So far I haven't found any related to the crow clade.

**Comment by hallmar** [comment]
It's my first contribution to a script! I'll have some non-alcohol beer tonight woohoo

NEXT UP: TelexO support

**Comment by hallmar** [comment]
fyi, the 2.2.0 release forgets to mention the new Crow Slew parameter that's TLI modifiable with the letter 'N' in the release!

**Comment by schollz** [comment]
Oh that's right! Would you mind adding the command? You can make a new file like this one: https://github.com/schollz/zxcvbn/blob/main/docs/builder/content/commands/release.md

**Comment by hallmar** [comment]
Done! :)

**Pull request merged**
